name: fishpi_environment
dependencies:
  - python=3.11  # Replace with the Python version your script requires
  - pip
  - numpy=1.25.2
  - pandas=2.1.1
  - matplotlib=3.8.0
  - pillow=10.0.1
  - tk


  - pip:
      - biopython==1.81
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.43.1
      - importlib-resources==6.1.0
      - kiwisolver==1.4.5
      - messagebox==0.1.0
      - packaging==23.2
      - pyparsing==3.1.1
      - pysimplegui==4.60.5
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - six==1.16.0
      - tkinterweb==3.21.1
      - tkinterx==0.0.9
      - tzdata==2023.3
      - zipp==3.17.0

channels:
  - defaults
  - conda-forge
