name: FishPi GUI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v4

    # Step 2: Set up Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Download TE sequence fasta files from Zenodo
    - name: Download TE sequence fasta files
      run: |
        wget -P files https://zenodo.org/record/13911872/files/GRCz11_ensembl_teseqs.fishpi.fasta.gz
        wget -P files https://zenodo.org/record/13911872/files/Onil_1.2_ensembl_teseqs.fishpi.fasta.gz
        wget -P files https://zenodo.org/record/13911872/files/oryLat2_ensembl_teseqs.fishpi.fasta.gz

        # Decompress the files after downloading
        gunzip files/GRCz11_ensembl_teseqs.fishpi.fasta.gz
        gunzip files/Onil_1.2_ensembl_teseqs.fishpi.fasta.gz
        gunzip files/oryLat2_ensembl_teseqs.fishpi.fasta.gz

    # Step 5: Install Xvfb for virtual display
    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    # Step 6: Start Xvfb (virtual display) and execute the script
    - name: Run FishPi script with virtual display
      run: |
        # Start virtual framebuffer
        Xvfb :99 -ac -screen 0 1280x1024x16 &
        
        # Sleep for a moment to ensure Xvfb has enough time to initialize
        sleep 8

        # Export DISPLAY environment variable
        export DISPLAY=:99

        # Run the Python script (this is the FishPi.py script that creates the GUI)
        python files/FishPi.py
      env:
        DISPLAY: ":99"

    # Step 7: List directory contents to verify file locations (for debugging purposes)
    - name: List directory contents
      run: ls -R
      working-directory: .
