name: FishPi Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download TE sequence fasta files
      run: |
        wget -P files https://zenodo.org/record/13911872/files/GRCz11_ensembl_teseqs.fishpi.fasta.gz
        wget -P files https://zenodo.org/record/13911872/files/Onil_1.2_ensembl_teseqs.fishpi.fasta.gz
        wget -P files https://zenodo.org/record/13911872/files/oryLat2_ensembl_teseqs.fishpi.fasta.gz

        # Decompress the files after downloading
        gunzip files/GRCz11_ensembl_teseqs.fishpi.fasta.gz
        gunzip files/Onil_1.2_ensembl_teseqs.fishpi.fasta.gz
        gunzip files/oryLat2_ensembl_teseqs.fishpi.fasta.gz

    - name: Run Unit Tests
      run: |
        pytest --maxfail=1 --disable-warnings

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Run GUI script with virtual display
      run: |
        # Start virtual framebuffer
        Xvfb :99 -ac -screen 0 1280x1024x16 &
        sleep 10
        export DISPLAY=:99

        # Run the FishPi.py script with a timeout
        python files/FishPi.py &
        sleep 5  # Let the GUI run for 5 seconds
        pkill -f FishPi.py || true
      env:
        DISPLAY: ":99"

    - name: List directory contents (for debugging)
      run: ls -R
      working-directory: .
