name: FishPi Python Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v4

    # Step 2: Set up Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: List files to verify file locations (for debugging purposes)
    - name: List directory contents
      run: ls -R
      working-directory: .

    # Step 5: Run FishPi script with error handling
    - name: Run FishPi script
      run: |
        set -e
        python files/FishPi.py || echo "Python script failed with exit code $?"
    - name: Display Python error logs if the script fails
      if: failure()
      run: |
        echo "Check for more details in the script output above"
