name: FishPi Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sed -i 's/PySimpleGUI==4.60.5/PySimpleGUI==5.0.8.2/' requirements.txt
          pip install -r requirements.txt
          # Install dependencies


      # Download required FASTA files
      - name: Download FASTA files
        run: |
          wget https://zenodo.org/record/13911872/files/GRCz11_ensembl_teseqs.fishpi.fasta.gz -O files/GRCz11_ensembl_teseqs.fishpi.fasta.gz
          wget https://zenodo.org/record/13911872/files/Onil_1.2_ensembl_teseqs.fishpi.fasta.gz -O files/Onil_1.2_ensembl_teseqs.fishpi.fasta.gz
          wget https://zenodo.org/record/13911872/files/oryLat2_ensembl_teseqs.fishpi.fasta.gz -O files/oryLat2_ensembl_teseqs.fishpi.fasta.gz
          gunzip files/*.fasta.gz  # Uncompress the files

      # Run unit tests (non-GUI)
      - name: Run unit tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings || true

  gui-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Download required FASTA files
      - name: Download FASTA files
        run: |
          wget https://zenodo.org/record/13911872/files/GRCz11_ensembl_teseqs.fishpi.fasta.gz -O files/GRCz11_ensembl_teseqs.fishpi.fasta.gz
          wget https://zenodo.org/record/13911872/files/Onil_1.2_ensembl_teseqs.fishpi.fasta.gz -O files/Onil_1.2_ensembl_teseqs.fishpi.fasta.gz
          wget https://zenodo.org/record/13911872/files/oryLat2_ensembl_teseqs.fishpi.fasta.gz -O files/oryLat2_ensembl_teseqs.fishpi.fasta.gz
          gunzip files/*.fasta.gz  # Uncompress the files

      # Install Xvfb
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      # Start virtual framebuffer and run GUI test
      - name: Run GUI test
        run: |
          Xvfb :99 -ac -screen 0 1280x1024x16 > xvfb.log 2>&1 &
          sleep 5  # Give Xvfb time to initialize
          export DISPLAY=:99
          # Run the Python GUI script with a timer to automatically close
          python files/FishPi.py || cat xvfb.log
